# Generated by Django 2.2.14 on 2020-08-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_data_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='task_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
