# Generated by Django 2.2.14 on 2020-08-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
